package metrics

const ComparisonsCalled = "comparisons_called"
const ExportsCalled = "exports_called"
const DeprecatedOperationsCalled = "deprecated_operations_called"
const DocumentsCalled = "documents_called"
const PackagesAndDashboardsCreated = "packages_and_dashboards_created"
const ReleaseVersionsPublished = "release_versions_published"
const ReleaseVersionsDeleted = "release_versions_deleted"
const GlobalSearchCalled = "global_search_called"
const GlobalSearchDefaultPublicationDateModified = "global_search_default_publication_date_modified"
const MCPSessionInitialized = "mcp_session_initialized"
const MCPLegacySearchToolCalled = "mcp_search_rest_operations_tool_called"
const MCPLegacyGetSpecToolCalled = "mcp_get_rest_operation_spec_tool_called"
const MCPLegacyGetDiffToolCalled = "mcp_get_rest_operation_diff_tool_called"
const MCPSearchToolCalled = "mcp_search_operations_tool_called"
const MCPGetSpecToolCalled = "mcp_get_operation_spec_tool_called"
const MCPGetDiffToolCalled = "mcp_get_operation_diff_tool_called"
const MCPGetDocumentToolCalled = "mcp_get_document_tool_called"
const MCPSearchV2ToolCalled = "mcp_search_operations_v2_tool_called"
const MCPListWorkspacePackagesToolCalled = "mcp_list_workspace_packages_tool_called"
const MCPListPackageVersionsToolCalled = "mcp_list_package_versions_tool_called"
const MCPListDdlEntitiesToolCalled = "mcp_list_ddl_entities_tool_called"
const MCPGetDdlEntityToolCalled = "mcp_get_ddl_entity_tool_called"
const MCPGetDdlEntityDiffToolCalled = "mcp_get_ddl_entity_diff_tool_called"
const MCPListMcpContractEntitiesToolCalled = "mcp_list_mcp_contract_entities_tool_called"
const MCPGetMcpContractEntityToolCalled = "mcp_get_mcp_contract_entity_tool_called"
const AIChatCalled = "ai_chat_called"
