CREATE TABLE locks (
    name VARCHAR PRIMARY KEY,
    instance_id VARCHAR NOT NULL,
    acquired_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 1
); 