-- Manual DDL table groups (analog of operation_group / grouped_operation,
-- without export templates, history and autogenerated prefix groups)
CREATE TABLE IF NOT EXISTS ddl_table_group
(
    package_id  varchar NOT NULL,
    version     varchar NOT NULL,
    revision    integer NOT NULL,
    group_name  varchar NOT NULL,
    group_id    varchar NOT NULL,
    description varchar,
    CONSTRAINT pk_ddl_table_group PRIMARY KEY (package_id, version, revision, group_name),
    CONSTRAINT ddl_table_group_group_id_key UNIQUE (group_id),
    CONSTRAINT "FK_ddl_table_group_published_version"
        FOREIGN KEY (package_id, version, revision)
            REFERENCES public.published_version (package_id, version, revision)
            ON UPDATE CASCADE ON DELETE CASCADE
);

-- Members of a dashboard group live in referenced package versions, and ddl_tables is managed
-- manually by the publish, cleanup and transition paths, so membership is validated by the
-- service on write rather than by a foreign key to ddl_tables.
CREATE TABLE IF NOT EXISTS grouped_ddl_table
(
    group_id      varchar NOT NULL,
    package_id    varchar NOT NULL,
    version       varchar NOT NULL,
    revision      integer NOT NULL,
    ddl_entity_id varchar NOT NULL,
    CONSTRAINT pk_grouped_ddl_table PRIMARY KEY (group_id, package_id, version, revision, ddl_entity_id),
    CONSTRAINT "FK_grouped_ddl_table_group"
        FOREIGN KEY (group_id) REFERENCES public.ddl_table_group (group_id)
            ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS grouped_ddl_table_entity_idx
    ON grouped_ddl_table (package_id, version, revision, ddl_entity_id);
