version: "3.9"
services:
  qubership-apihub-ui:
    image: ghcr.io/netcracker/qubership-apihub-ui:main
    environment:
      APIHUB_BACKEND_ADDRESS: "host.docker.internal:8090"
      APIHUB_NC_SERVICE_ADDRESS: "host.docker.internal:8091"
    ports:
      - "8081:8080"
    restart: unless-stopped 