# Section with PostgreSQL database connection parameters
database:
  # Mandatory; PostgreSQL database host ; If not set, default value: localhost; Example: postgres.example.com
  host: 'localhost'
  # Mandatory; PostgreSQL database port; If not set, default value: 5432; Example: 5432
  port: 5432
  # Mandatory; Logical database in PostgreSQL cluster for APIHUB. Manual pre-creation required; If not set, default value: apihub; Example: apihub_backend_prod_db
  name: 'apihub'
  # Mandatory; User for APIHUB_POSTGRESQL_DB_NAME database; If not set, default value: apihub; Example: apihub_backend_prod_admin
  username: 'apihub'
  # Mandatory; Password for APIHUB_POSTGRESQL_USERNAME user.; If not set, default value: apihub; Example: apihub_backend_prod_password
  password: 'apihub'

# Section with all security (authentication and authorization) parameters
security:
  # Optional; Enables production mode - login under local apihub users is prohibited in this mode. In this mode only external IdP auth is possible; If not set, default value: true; Example: true
  productionMode: true  # set to false at your own risk
  # Section with parameters for configuring JWT tokens issued by APIHUB
  jwt:
    # Mandatory; Self generated private PKCS#8 private key, base64 encoded. The RSA key length must be at least 2048 bits and no more than 4096 bits to ensure a balance between security and performance. Used for siging of JWT tokens issued by APIHUB, must be unique fore each APIHUB instance; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
    privateKey: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURHcVlTcVJKYWdiMFk5DQpEc01HSklXclBQdERKVkg1dEx6Y01CS0sxeFQ4OGg2bElFS0xMdnNyWW4rRGFEYjIyMSt1ODFGU1lRUVg5TGlPDQowdlF2aWJNSkJURkQ5clA1VmFldVZwS2lhQTNaczczUzMzaDZrejIrdmlpb25YRllwYXBOVUlQSjA0QUxuSkl1DQo5V0JseFFyVTNMREkrUUNDSXB0N3RGZHpKMEV5Q0p0bVR4QXpodDFiREN3bmxyb0crb2JXaGFxYkhxR3JOSWxODQpuT0FyNmxRY2Y5a05aOGRyNTBrdWh4d1d2aEE4OTZaSDhhS2RIRVdZZTdhb0xLNURTN2hyTWhGRVBrZGpHR2NNDQp4aVVSN1lVMEhWRFZjaDV3cVgxUVJ3SWxONDZqK1RpRFp1d3FiU0c0eGMyMHh3bTE0TkV4RFpEbS8rZ08yeHVGDQpiLzB4aCs4ekFnTUJBQUVDZ2dFQUJWcWxDSXJMRlB4ZDh3cklpajlPelpySTNvY1JmdXRZZWhjOHlMSHcyOHlhDQpLdFVkdm9pdXo3anJ1dHJHK1BzbEhmUTNlbFAxOXhVdlhUd3VQSkxSRkpFRmhud09LODM1Yjk3ZlRhRHpPVWJ3DQoySG96ZktQUllZWSt2VFkzZGhTT3lrM1c4SCtPVjhIRmIxb0ZXaU40ODJSOGx6enpBem1FNGFKWktZc1JzWXVaDQpJN3BRblE0MzZqSytMb201RzRHbW5pMDM2ZXpPUTNWYXZTUjJTaVBob3VoUTlQYU5BK0pnNXZwR0Y5NGRWcXhhDQpJMXVUc1MvaUgxSmdrWWtoUndWc0hPMFhiZFJTd0ZwZUdnUjU0ZUJNY2NrcmVJaDAvSDZabWpXd1ROblpOMzV5DQpGMFljWU8yaHRVU1RiYUdaQm9HdUhmdm13amc0UE5JTXJQazkwRVhYZ1FLQmdRRHEyMWZLdk0wcjkxaXlONGdhDQpEZC9nVWM5N1NBVTRUWCtLQ3RIcHpIbXRuc2hlSjQwZ0twVW9sT1V1dDJiQk56dTNjZVEweUI0eGpIYVppSEoxDQplY0pCMmZHYmVodHBpTldoUndtSE9CZlJqQXF2WUt0L2tPM3B1WENUeUZYM1hlaW9PSGJWeVFjOW1HMTYycGpyDQowelBPT3lSRjdrbzc2Y2d1TVhheXZpaXVrd0tCZ1FEWWpBTGYrMjBvK0pCWW5BYWpGSU5mNlBtTytRNUtxS1d6DQpvS3lXbTFldEVEQlNDSFdmN1FRT1JzNzVON0hFeXAvdDM1QWxpcnJGdUxIbGRmc0VYL3B5aVRGTDRBeFRubGhvDQpwWkxGM0dENFhVMUJRcFJqRDE4RHNXQ05HN0lBcS9BUG05S3F2bFRCRGw3Qk1DVHJYNjg0aWpXc2tMSCtERzV5DQpWSE1aVnErQTRRS0JnUUNUeE15NU9BL1QwUDVTcTlRTHFKMHJFKzU2Ly9hZzFVb2cvZXZUc2g4QkdiMnlXQ3BZDQppZEp0eFRscUttVVJ2d0hveTFVdHpKZ0t6dmswWXdDNVg1SFZReDdjbDNpMTd5MlRHeElvclNkM1ppaTI3aGtaDQoyNE9HSW5KdDJZZ1ZhMVhldWlBekpSaFVMaHI4U0p3ZERUYzBWRXZmWUMzL0Fubzhia3pqNi9mRzF3S0JnSE0yDQp3MHpTcERpNVQydWwwQzR5ZXRlcnlDUFd4VkRadkJmL2MvUkp3SE5XK3E2YXk2S0VZN1VJM1pSaG1wYSt6Q3F1DQoyUzN3U3dGcURGU3UyaGh3ekhybUhiRm1Db2p1NWREL3owQ3d5WE03aVNBZ3dYeVhNQkZ4N1pJR1cwWGFOVWJJDQp2R1NXRWRnSndrWjlUQmRqZUlIWG4wa3FUMW1BMmI3QXllQ0FhNjVoQW9HQkFPak00SVdJZ0JSY1JiTW9vdmpjDQppSmpLOUZZdTM1b0dSVnZNOHNzUFpQZTdJMFVZWGh3VVJHTlpwV25kVEhGTFhEYU5DTVFNQTlBOTdpUUFHZjUzDQpaMjNyMEN3cmdaQVVMOUg4TCt1STNTaWVrZndHTEpaOCtmdzdvRjhwSWlNMFl0MklYQXU4bG0xRkVhTzdPREl2DQpGTTF4YTRnYVpLc005Wldkd0NnTFBYclANCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg=='
    # Optional; Duration in seconds for access tokens issued by APIHUB; If not set, default value: 1800; Example: 1800
    accessTokenDurationSec: 1800
    # Optional; Duration in seconds for refresh tokens issued by APIHUB; If not set, default value: 43200; Example: 43200
    refreshTokenDurationSec: 43200
  # Mandatory; Factual APIHUB server URL in your environment.; If not set, default value: ""; Example: https://apihub.example.com
  apihubExternalUrl: 'https://apihub.example.com'
  # Optional; Set to true to enable apihub playground work without authtorization. Dangerous. Not recommended; If not set, default value: false; Example: true
  insecureProxy: false
  # Optional; Allowed list of hosts that are accepted for proxy(playground) requests.; If not set, default value: []; Example: [example.com]
  allowedHostsForProxy: 
    - example.com
    - localhost
  # Optional; Allows to set extra allowed origins to CORS header. Used for FE debugging. Should be empty on prod envs.; If not set, default value: []; Example: [https://localhost:5137]
  allowedOrigins: 
    - https://localhost:5137
  # Optional; Enables automatic login with the configured identity provider instead of showing the APIHUB login page; If not set, default value: false; Example: true
  autoLogin: false
  # Optional; To be deleted, WA for smooth upgrade of exisiting deployments; If not set, default value: true; Example: false
  legacySaml: true
  # Optional; List of external identity providers to use for authentication; OIDC and SAML types are supported. If not set, default value: ""; Example: external-idp
  externalIdentityProviders:
    # Mandatory; ID for external identity provider; If not set, default value: ""; Example: external-saml-idp
    - id: 'external-saml-idp'
      # Optional; Display name for external SAML identity provider; If not set, default value: ""; Example: External Identity Provider
      displayName: 'test'
      # Optional; SVG image for external SAML identity provider logo; If not set, default value: ""; Example: <svg fill="#000000" width="800px"...
      imageSvg: ''
      # Mandatory; Protocol for external identity provider; If not set, default value: ""; Example: SAML
      protocol: 'SAML'
      # Optional; SAML configuration for external identity provider, required if protocol is 'SAML'; If not set, default value: ""; Example: 
      samlConfiguration:
        # Optional; SAML metadata URL. Required for SAML configuration; If not set, default value: ""; Example: https://idp.example.com/FederationMetadata/2007-06/FederationMetadata.xml
        metadataUrl: ''
        # Optional; SAML server certificate, base64 encoded. Required for SAML configuration; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
        certificate: '' 
        # Optional; SAML server private key, base64 encoded. Required for SAML configuration; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
        privateKey: ''
    # Mandatory; ID for external identity provider; If not set, default value: ""; Example: external-oidc-idp   
    - id: 'external-oidc-idp'
      # Optional; Display name for external OIDC identity provider; If not set, default value: ""; Example: External Identity Provider
      displayName: 'test'
      # Optional; SVG image for external OIDC identity provider logo; If not set, default value: ""; Example: <svg fill="#000000" width="800px"...
      imageSvg: ''
      # Mandatory; Protocol for external identity provider; If not set, default value: ""; Example: OIDC
      protocol: 'OIDC'
      # Optional; OIDC configuration for external identity provider, required if protocol is 'OIDC'; If not set, default value: ""; Example: 
      oidcConfiguration:
        # Optional; OIDC identity provider URL. Required for OIDC configuration; If not set, default value: ""; Example: https://idp.example.com/realms/apihub
        providerUrl: ''
        # Optional; OIDC client ID. Required for OIDC configuration; If not set, default value: ""; Example: apihub
        clientId: ''
        # Optional; OIDC client secret. Required for OIDC configuration; If not set, default value: ""; Example: l5cKFvwDRSnhBErE9LUGeBk0dqqFB7No
        clientSecret: ''

  # Section with LDAP integration parameters. LDAP integration is used for User search. Makes sense only if SAML/OIDC integration enabled.
  ldap:
    # Optional; LDAP server URL. Required for SAML integration for syncing users information; If not set, default value: ""; Example: ldap://ldap.example.com:389
    server: 'ldap://ldap.example.com:389'
    # Optional; LDAP User used for connecting to LDAP server; If not set, default value: ""; Example: x_apihub
    user: 'x_apihub'
    # Optional; Password for LDAP User; If not set, default value: ""; Example: x_apihub_password
    password: 'x_apihub_password'
    # Optional; Base DN to search users in; If not set, default value: ""; Example: organization
    baseDN: 'organization'
    # Optional; Organization unit to search users in; If not set, default value: ""; Example: example
    organizationUnit: 'example'
    # Optional; Search base to search users in; If not set, default value: ""; Example: com
    searchBase: 'com'

# Section with zero-day settings
zeroDayConfiguration:
  #TODO: need to provide requirements for the value of accessToken
  # Mandatory; Default system access token (any string). The token will be provisioned automatically during startup; If not set, default value: ""; Example: access-token-12345
  accessToken: 'access-token-12345'
  # Optional; Default local admin user login. If set - this admin user will be created automatically.; If not set, default value: ""; Example: admin@example.com
  adminEmail: 'admin@example.com'
  # Optional; Default local admin user password; If not set, default value: ""; Example: admin-password
  adminPassword: 'admin-password'

# Section with technical parameters
technicalParameters:
  # Optional; Base path for binary and static files, default value: .; Example: /tmp
  basePath: '.'
  # Optional; Backend version; If not set, default value: unknown; Example: 0.0.0
  backendVersion: '0.0.0'
  # Optional; Listen address for APIHUB backend, can be used to avoid port conflicts in case of run on bare metall; If not set, default value: :8080; Example: :8080
  listenAddress: ':8080'

# Section with various parameters related to APIHUB business logic
businessParameters:
  # Optional; Links to be shown under (i) button in UI; If not set, default value: []; Example: [https://example.com]
  externalLinks: 
    - https://example.com
  # Optional; Default workspace ID for Agent UI; If not set, default value: ""; Example: QS
  defaultWorkspaceId: 'QS'
  # Optional; Regex pattern for releases names validation.; If not set, default value: .*; Example: ^2023\.1$
  releaseVersionPattern: '.*'
  # Optional; Limit for uploaded package size in order to avoid OOM; If not set, default value: 50; Example: 50
  publishArchiveSizeLimitMb: 50
  # Optional; Limit for uploaded file (inside package) size in order to avoid OOM; If not set, default value: 15; Example: 20
  publishFileSizeLimitMb: 15
  # Deprecated. Required for Editor feature. Size limit for the branch content.
  branchContentSizeLimitMb: 50
  # Optional; If set - footer with this text is shown for all APIHUB users in APIHUB UI. Designed for maintenance windows notifications.; If not set, default value: ""; Example: Maintenance scheduled on 2023-10-15
  systemNotification: ''
  # Optional; Set to true to fail build on broken refs; If not set, default value: true; Example: true
  failBuildOnBrokenRefs: true


# Section with monitoring configuration for APIHUB
# APIHUB backend is using Prometheus for monitoring and Grafana for visualization
monitoring:
  # Optional; Enables creation of Service Monitor. If not set, default value: false; Example: true
  enabled: false

# Section with S3 storage integration parameters.
s3Storage:
  # Optional; Set to true to enable S3 integration. S3 is used for store temporary relatively large files.; If not set, default value: false; Example: true
  enabled: false
  # Optional; S3 endpoint for client connection; If not set, default value: ""; Example: s3.example.com
  url: 'https://s3.example.com'
  # Optional; Access Key ID from S3 storage; If not set, default value: ""; Example: s3-access-key
  username: 's3-access-key'
  # Optional; Secret key for S3 storage access; If not set, default value: ""; Example: s3-secret-key
  password: 's3-secret-key'
  # Optional; Certificate for accessing S3 storage; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
  crt: ''
  # Optional; Bucket name in S3 storage; If not set, default value: ""; Example: apihub-bucket
  bucketName: 'apihub-bucket'
  # Optional; Set to true to store only build results (less data amout) in S3 storage; If not set, default value: false; Example: true
  storeOnlyBuildResult: false

# Parameters for APIHUB Editor feature. Deprecated. Will be removed in future releases.
editor:
  disabled: true
  gitlabUrl: ''
  clientId: ''
  clientSecret: ''

# Section with Olric configuration.
olric:
  # Optional; Discovery mode for Olric. If not set, default value: local; Example: local
  discoveryMode: 'local'
  # Optional; Replica count for Olric. If not set, default value: 1; Example: 1
  replicaCount: 1
  # Optional; Namespace for Olric discovery. If not set, default value: ""; Example: apihub
  namespace: 'apihub'