version: "3.9"
services:
  qubership-apihub-build-task-consumer:
    image: ghcr.io/netcracker/qubership-apihub-build-task-consumer:main
    environment:
      APIHUB_BACKEND_ADDRESS: "host.docker.internal:8090"
      APIHUB_API_KEY: "123123"
    ports:
      - "3000:3000"
    restart: unless-stopped 