openapi: 3.0.3
info:
  title: APIHUB system administrators API
  description: |
    The API is for system administrators only.
  license:
    name: qubership
    url: https://qubership.org
  version: "2024.2"
  x-nc-api-audience: BWC
externalDocs:
  description: Find out more about package
  url: https://qubership.org/APIHUB
servers:
  - url: https://{apihub}.qubership.org
    description: APIHUB server
    variables:
      apihub:
        description: Name of the APIHUB server.
        enum:
          - apihub
          - dev.apihub
          - staging.apihub
        default: apihub
security:
  - BearerAuth: []
  - CookieAuth: []
tags:
  - name: Transition
    description: Operations to move packages
  - name: System
    description: System operations
  - name: Admin
    description: APIs for technical administration.

paths:
  "/api/v2/admin/transition/move":
    post:
      tags:
        - Transition
      summary: Move package
      description: Change package id, i.e. rename it or change parent. Async operation, result is returned by id.
      operationId: movePackage
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      requestBody:
        description: Package coordinates
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  description: package id that needs to be moved
                to:
                  type: string
                  description: destination package id
                overwriteHistory:
                  type: boolean
                  description: Enable force move for already used 'old' package id(which now redirects to some new one). In this case existing transition record will be lost and there would be no more redirect.
            examples: {}
        required: true

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Move package response
                type: object
                properties:
                  id:
                    description: Move process id
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                IncorrectInputParams:
                  $ref: "#/components/examples/IncorrectInputParameters"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "404":
          description: Not found or incorrect 'from' ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InternalServerError:
                  $ref: "#/components/examples/InternalServerError"

  /api/v2/admin/transition/move/{id}:
    get:
      tags:
        - Transition
      summary: Get move status
      description: |
        Get status of the move operation by id.
      operationId: getMoveStatus
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      parameters:
        - name: id
          description: Move operation id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransitionStatus"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "404":
          description: Not found or incorrect ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InternalServerError:
                  $ref: "#/components/examples/InternalServerError"

  /api/v2/admin/transition/activity:
    get:
      tags:
        - Transition
      summary: List completed transition activities
      description: |
        List completed transition activities
      operationId: listActivities
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      parameters:
        - name: offset
          in: query
          description: Transition activities offset
          schema:
            type: number
            default: 0
        - name: limit
          in: query
          description: Maximun items in response
          schema:
            type: number
            default: 100
            maximum: 100
            minimum: 1
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Transition activities list
                type: object
                properties:
                  changes:
                    type: array
                    items:
                      $ref: "#/components/schemas/TransitionStatus"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InternalServerError:
                  $ref: "#/components/examples/InternalServerError"
  /api/v2/admin/transition:
    get:
      tags:
        - Transition
      summary: List transitions
      description: |
        List full transition mapping
      operationId: listPackageTransitions
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Transition activities list
                type: object
                properties:
                  changes:
                    type: array
                    items:
                      type: object
                      properties:
                        oldPackageId:
                          description: Package id that was before transition
                          type: string
                        newPackageId:
                          description: New package id after transition
                          type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InternalServerError:
                  $ref: "#/components/examples/InternalServerError"
  /api/v2/admin/system/stats:
    get:
      tags:
        - System
      summary: Get system statistics
      description: |
        Retrieves system-wide statistics including business entities count, build statistics, and database size information.
      operationId: getSystemStats
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      responses:
        "200":
          description: System statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemStats"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples: {}
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InternalServerError:
                  $ref: "#/components/examples/InternalServerError"
  /api/v1/globalConfiguration:
    patch:
      tags:
        - Admin
      summary: Update global configuration parameters
      description: >
        Update global configuration parameters.
        * If the parameter is not transmitted in request - its value stays
        unchanged.
      operationId: patchGlobalConfigurationParameters
      security:
        - BearerAuth: []
        - CookieAuth: []
        - api-key: []
      requestBody:
        description: Global configuration update parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                versionPattern:
                  type: string
                  description: >
                    Regular expression pattern for validating version names.
                    Must be a valid regex.
                  example: ^[A-Za-z0-9_.~\-]+$
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationParameters'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      description: An error description
      type: object
      properties:
        status:
          description: HTTP Status Code
          type: number
        code:
          description: Internal string error code. Mandatory in response.
          type: string
        message:
          description: The attribute contains an error message.
          type: string
        params:
          type: object
          description: Message parameters
          example:
            id: 12345
            type: string
        debug:
          description: The attribute contains debug details (e.g. stack-trace). Presented in the error response only on Dev/Test environments if corresponding logging level is enabled.
          type: string
      required:
        - status
        - code
        - message
    TransitionStatus:
      type: object
      properties:
        id:
          type: string
          description: Move operation id
        trType:
          type: string
          description: Transition type
        fromId:
          type: string
          description: Source package id
        toId:
          type: string
          description: Destination package id
        status:
          type: string
          description: Operation status
        startedBy:
          type: string
          description: User who started the operation
        startedAt:
          type: string
          description: Time when the operation was started
        finishedAt:
          type: string
          description: Time when the operation was finished
        progressPercent:
          type: integer
          format: int32
          description: Percent of complete. Values 0-100
        affectedObjects:
          type: integer
          format: int32
          description: Number of affected rows in DB
        completedSerialNumber:
          type: integer
          format: int32
          description: Serial number of completed transition
    BuildsCount:
      type: object
      description: Statistics for a specific build type
      properties:
        notStarted:
          type: integer
          description: Number of builds not started
        running:
          type: integer
          description: Number of builds currently running
        failedLastWeek:
          type: integer
          description: Number of builds that failed in the last week
        succeedLastWeek:
          type: integer
          description: Number of builds that succeeded in the last week
        restartsLastWeek:
          type: integer
          description: Number of builds that were restarted in the last week
    SystemStats:
      type: object
      description: System-wide statistics
      properties:
        businessEntities:
          type: object
          description: Counts of various business entities in the system
          properties:
            workspaces:
              type: integer
              description: Number of workspaces
            deletedWorkspaces:
              type: integer
              description: Number of deleted workspaces
            groups:
              type: integer
              description: Number of groups
            deletedGroups:
              type: integer
              description: Number of deleted groups
            packages:
              type: integer
              description: Number of packages
            deletedPackages:
              type: integer
              description: Number of deleted packages
            dashboards:
              type: integer
              description: Number of dashboards
            deletedDashboards:
              type: integer
              description: Number of deleted dashboards
            revisions:
              type: integer
              description: Number of revisions
            deletedRevisions:
              type: integer
              description: Number of deleted revisions
            documents:
              type: integer
              description: Number of documents
            operations:
              type: integer
              description: Number of operations
            versionComparisons:
              type: integer
              description: Number of version comparisons
        builds:
          type: object
          description: |
            Statistics about builds by build type.
          properties:
            build:
              $ref: "#/components/schemas/BuildsCount"
            changelog:
              $ref: "#/components/schemas/BuildsCount"
            documentGroup:
              $ref: "#/components/schemas/BuildsCount"
            exportRestDocument:
              $ref: "#/components/schemas/BuildsCount"
            exportRestOperationsGroup:
              $ref: "#/components/schemas/BuildsCount"
            exportVersion:
              $ref: "#/components/schemas/BuildsCount"
            mergedSpecification:
              $ref: "#/components/schemas/BuildsCount"
            reducedSourceSpecifications:
              $ref: "#/components/schemas/BuildsCount"
        databaseSize:
          type: array
          description: Information about database table sizes
          items:
            type: object
            properties:
              tableName:
                type: string
                description: Name of the database table
              rowEstimate:
                type: number
                format: float
                description: Estimated number of rows in the table
              totalSize:
                type: string
                description: Total size of the table including all related data
              indexSize:
                type: string
                description: Size of the table's indexes
              toastSize:
                type: string
                description: Size of the table's TOAST data
              tableSize:
                type: string
                description: Size of the actual table data
              totalSizeShare:
                type: number
                format: float
                description: Proportion of the total database size that this table uses
    ConfigurationParameters:
      description: Global configuration parameters 
      type: object
      properties:
        versionPattern:
          type: string
          description: >
            Regular expression pattern used for validating version names. Used
            globally across the system.
          example: ^[A-Za-z0-9_.~\-]+$
  examples:
    IncorrectInputParameters:
      description: Incorrect input parameters
      value:
        status: 400
        code: "APIHUB-COMMON-4001"
        message: "Incorrect input parameters"
    InternalServerError:
      description: Default internal server error
      value:
        status: 500
        code: "APIHUB-8000"
        reason: "InternalServerError"
        message: "InternalServerError"
  securitySchemes:
    BearerAuth:
      type: http
      description: Bearer token authentication. Default secutity scheme for API usage.
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: apihub-access-token
      description: Authentication via the `apihub-access-token` cookie.
    api-key:
      type: apiKey
      description: Api-key authentication.
      name: api-key
      in: header