name: E2E CI Workflow 

on:
  push:
    branches:
      - "**"     
    tags:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-docker-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@e2e
    with:
        name: qubership-apihub-backend
        file: Dockerfile
        context: ""
        platforms: linux/amd64,linux/arm64
        labels: |
            maintainer=qubership

  call-e2e-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/e2e-ci.yml@e2e
    needs: call-docker-ci-workflow
    # if: github.event_name == 'pull_request'
    with:
      postman-collections-run: false
      postman-collections-list: './e2e/1_1_Smoke_Portal.postman_collection.json,./e2e/2_1_Negative_Portal.postman_collection.json,./e2e/3_1_Stories_Bugs.postman_collection.json,./e2e/4_Access_control.postman_collection.json'
      backend_image_tag: ${{ needs.call-docker-ci-workflow.outputs.image_tag }}
    secrets:
      APIHUB_ACCESS_TOKEN: ${{ secrets.APIHUB_ACCESS_TOKEN }}
      APIHUB_ADMIN_EMAIL: ${{ secrets.APIHUB_ADMIN_EMAIL }}
      APIHUB_ADMIN_PASSWORD: ${{ secrets.APIHUB_ADMIN_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      NPMRC: ${{ secrets.NPMRC }}