name: Docker Build and publish workflow

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-docker-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@v4
    with:
      name: qubership-apihub-backend
      file: Dockerfile
      context: ""
      platforms: linux/amd64,linux/arm64
