name: E2E CI Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      compose-repository-branch:
          description: "Branch to clone"
          type: string
          default: "main"
      postman-collections-run:
          description: "Flag for executing postman collections"
          type: boolean
          default: true
      postman-repository-branch:
          description: "https://github.com/Netcracker/qubership-apihub-postman-collections branch to clone"
          type: string
          default: "main"
      postman-collections-list:
          description: "Collections to execute"
          type: string
          default: "./e2e/1_1_Smoke_Portal.postman_collection.json,./e2e/2_1_Negative_Portal.postman_collection.json,./e2e/3_1_Stories_Bugs.postman_collection.json,./e2e/4_Access_control.postman_collection.json"
      playwright-tests-run:
        description: "Flag for executing playwright tests"
        type: boolean
        default: true
      playwright-repository-branch:
          description: "https://github.com/Netcracker/qubership-apihub-ui-tests branch to clone"
          type: string
          default: "main"

jobs:
  call-e2e-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/e2e-ci.yml@e2e
    with:
      compose-repository-branch: ${{ github.event.inputs.compose-repository-branch || 'main' }}
      postman-collections-run: ${{ github.event.inputs.postman-collections-run || true}}
      postman-repository-branch: ${{ github.event.inputs.postman-repository-branch || 'main' }}
      postman-collections-list: ${{ github.event.inputs.postman-collections-list || './e2e/1_1_Smoke_Portal.postman_collection.json' }}
      playwright-repository-branch: ${{ github.event.inputs.playwright-repository-branch || 'main' }}
      playwright-tests-run: ${{ github.event.inputs.playwright-tests-run || true }}
    secrets:
      APIHUB_ACCESS_TOKEN: ${{ secrets.APIHUB_ACCESS_TOKEN }}
      APIHUB_ADMIN_EMAIL: ${{ secrets.APIHUB_ADMIN_EMAIL }}
      APIHUB_ADMIN_PASSWORD: ${{ secrets.APIHUB_ADMIN_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
