name: E2E CI Workflow
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    

jobs:
  call-e2e-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/e2e-ci.yml@e2e
    with:
      compose-repository-url: "https://github.com/Netcracker/qubership-apihub"
      compose-repository-branch: "main"
      compose-repository-compose-folder: "docker-compose"
      compose-repository-compose-file: "docker-compose.yml"
      postman-collections-run: true
      postman-repository-url: "https://github.com/Netcracker/qubership-apihub-postman-collections"
      postman-repository-branch: "main"
      postman-collections-list: "./e2e/1_1_Smoke_Portal.postman_collection.json"
    secrets:
      APIHUB_ACCESS_TOKEN: ${{ secrets.APIHUB_ACCESS_TOKEN }}
      APIHUB_ADMIN_EMAIL: ${{ secrets.APIHUB_ADMIN_EMAIL }}
      APIHUB_ADMIN_PASSWORD: ${{ secrets.APIHUB_ADMIN_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
